django_app/instagram/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from . import views

# from django.contrib.staticfiles import views


urlpatterns = [
                  url(r'^admin/', admin.site.urls),
                  url(r'^member/', include('member.urls')),
                  url(r'^post/', include('post.urls')),
                  url(r'^$', views.index, name="index"),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# if settings.DEBUG:
#     urlpatterns += [
#         url(r'^static/(?P<path>.*)$', views.serve)
#     ]

django_app/post/urls.py
from django.conf.urls import url

from . import views

app_name = 'post'
urlpatterns = [
    url(r'^$', views.post_list, name='post-list'),
    url(r'^(?P<post_id>[0-9]+)/$', views.post_detail, name='post-detail', ),
    url(r'^(?P<post_id>[0-9]+)/comment/add/$', views.comment_add, name='comment_add', ),
    url(r'^(?P<post_id>[0-9]+)/like/toggle$', views.post_like_toggle, name='post_like_toggle', ),
    # url(r'^(?P<post_id>[0-9]+)/comment/(?P<comment_id>[0-9]+)/delete/$',
    #     views.comment_delete,
    url(r'^(?P<post_id>[0-9]+)/comment/(?P<comment_id>[0-9]+)/delete/$',
        views.comment_delete,
        name='comment_delete', ),
    url(r'^add/$', views.post_add, name='post-add'),
    url(r'^(?P<post_id>[0-9]+)/delete/$', views.post_delete, name='post_delete'),
]

django_app/post/models.py
from django.db import models

from member.models import MyUser


class Post(models.Model):
    author = models.ForeignKey(MyUser)
    photo = models.ImageField('Profile Picture', blank=True, upload_to="post")
    # photo_height = models.PositiveIntegerField(null=True, blank=True, editable=False, default="100")
    # photo_width = models.PositiveIntegerField(null=True, blank=True, editable=False, default="100")

    like_users = models.ManyToManyField(MyUser,
                                        through="PostLike",
                                        # through_fields=("user", "post"),
                                        related_name="like_post_set"
                                        )
    # like_post_set: user에서 like한  post 볼때
    content = models.TextField(blank=True)

    def __str__(self):
        return 'Post [{}]'.format(self.id)

    def toggle_like(self, user):
        pl_list = PostLike.objects.filter(post=self, user=user)
        PostLike.objects.create(post=self, user=user) if not pl_list.exists() else pl_list.delete()
        # pl_list.delete() if pl_list.exists() else PostLike.objects.create(post=self, user=user)

        # 현재 인자로 전달된 user가 해당 post를 like한 적이 있는지 검사
        # if pl_list.exists():
        #     # 햇을 경우 삭제 remove/add 사용불가 중간자 사용했기때문에
        #     pl_list.delete()
        # else:
        #     # 없을 경우 생성
        #     PostLike.objects.create(post=self, user=user)

    def add_comment(self, user, new_comment):
        return self.comment_set.create(
            author=user,
            content=new_comment
        )

    @property
    def like_count(self):
        return self.like_users.count()

    @property
    def comment_count(self):
        # post에서 Comment
        return self.comment_set.count()


# intermediary btw MyUser and Post
class PostLike(models.Model):
    user = models.ForeignKey(MyUser)
    post = models.ForeignKey(Post)
    created_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        # 한 user가 post를 한번만 like하도록 (중복으로 like 불가하게
        unique_together = (
            ('user', 'post')
        )

    def __str__(self):
        return "Post {}\'s Like {} ".format(
            self.post_id,
            self.id,
        )


class Comment(models.Model):
    author = models.ForeignKey(MyUser, )
    post = models.ForeignKey(Post, )
    content = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True,)

    def __str__(self):
        return "Post [{}]\'s  Comment {} by Author []".format(
            self.post_id,
            self.id,
            self.author.id,
        )

django_app/post/models/comment.py
from django.conf import settings

from member import models
from member.models import MyUser
from post.models.post import Post
from django.db import models


__all__ = (
    'Comment',
)


class Comment(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL )
    post = models.ForeignKey(Post,)
    content = models.CharField(max_length=45)
    created_date = models.DateTimeField(auto_now_add=True, )

    def __str__(self):
        return "Post [{}]\'s  Comment {} by Author []".format(
            self.post_id,
            self.id,
            self.author.id,
        )

django_app/post/models/post.py
from django.conf import settings
from django.db import models

from member.models import MyUser

__all__ = (
    'Post',
    'PostLike',
)


class PostManager(models.Manager):
    def visible(self):
        return super().get_queryset().filter(is_visible=True)


class PostUserVisibleManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(is_visible=True)


class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL)
    photo = models.ImageField('Profile Picture', blank=True, upload_to="post")
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL,
                                        through="PostLike",
                                        # through_fields=("user", "post"),
                                        related_name="like_post_set"
                                        )
    # like_post_set: user에서 like한  post 볼때
    # content = models.TextField(blank=True)
    created_date = models.DateTimeField(auto_now_add=True)
    is_visible = models.BooleanField(default=True)

    objects = PostManager()
    visibles = PostUserVisibleManager()

    def __str__(self):
        return 'Post [{}]'.format(self.id)

    class Meta:
        ordering = ('-id',)

    def toggle_like(self, user):
        pl_list = PostLike.objects.filter(post=self, user=user)
        PostLike.objects.create(post=self, user=user) if not pl_list.exists() else pl_list.delete()
        # pl_list.delete() if pl_list.exists() else PostLike.objects.create(post=self, user=user)

        # 현재 인자로 전달된 user가 해당 post를 like한 적이 있는지 검사
        # if pl_list.exists():
        #     # 햇을 경우 삭제 remove/add 사용불가 중간자 사용했기때문에
        #     pl_list.delete()
        # else:
        #     # 없을 경우 생성
        #     PostLike.objects.create(post=self, user=user)

    def add_comment(self, user, new_comment):
        return self.comment_set.create(
            author=user,
            content=new_comment
        )

    @property
    def like_count(self):
        return self.like_users.count()

    @property
    def comment_count(self):
        # post에서 Comment
        return self.comment_set.count()


# intermediary btw MyUser and Post
class PostLike(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    post = models.ForeignKey(Post)
    created_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        # 한 user가 post를 한번만 like하도록 (중복으로 like 불가하게
        unique_together = (
            ('user', 'post')
        )

    def __str__(self):
        return "Post {}\'s Like {} ".format(
            self.post_id,
            self.id,
        )

django_app/post/forms.py
from django import forms
from django.forms import ModelForm

from post.models import Comment


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['content']


class PostForm(forms.Form):
    content = forms.CharField(required=False)
    photo = forms.ImageField(widget=forms.ClearableFileInput(attrs={'multiple': True}))


# class FileFieldForm(forms.Form):
#     file_field = forms.FileField()




    # class Meta:
    #     model=Post
    #     fields = ['photo',]

django_app/post/views/comment.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render

from post.forms import CommentForm
from post.models import Post, Comment

__all__ = (
    'comment_add',
    'comment_delete',
)

@login_required
def comment_add(request, post_id):
    if request.method == "POST":
        user = request.user
        form = CommentForm(data=request.POST)
        if form.is_valid():
            content = form.cleaned_data['content']
            post = Post.objects.get(id=post_id)
            post.add_comment(user, content)
            return redirect('post:post-list')
        else:
            post = Post.objects.get(id=post_id)
            context = {
                'post': post
                # 'comment_list': Post.comment_set.all(),
            }
        return render(request, 'post/post-list.html', context)

@login_required
def comment_delete(request, post_id, comment_id):
    if request.method == "POST":
        post = Post.objects.get(id=post_id)
        comment = Comment.objects.get(post=post, id=comment_id)
        if comment.author == request.user:
            comment.delete()
        return redirect('post:post-list')

django_app/post/views/post.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

from post.forms import CommentForm, PostForm
from post.models import Post

__all__ = (
    'post_list',
    'post_detail',
    'post_like_toggle',
    'post_delete',
    'post_add',
)


def post_list(request):
    context = {
        'post_list': Post.objects.filter(is_visible=True)
    }
    # if form

    return render(request, 'post/post-list.html', context)


# def comment_add(request, author, content ):


def post_detail(request, post_id):
    post = Post.objects.get(id=post_id)
    comment_form = CommentForm()
    context = {
        'post': post,
        'comment_form': comment_form,
        # 'comment_list': Post.comment_set.all(),

    }

    return render(request, 'post/post-detail.html', context)

@login_required
def post_like_toggle(request, post_id):
    if request.method == "POST":
        post = Post.objects.get(id=post_id)
        post.toggle_like(user=request.user)
        # return redirect('post:post-detail', post_id=post_id)
        return redirect('post:post-list')

@login_required
def post_delete(request, post_id, db_delete=False):
    if request.method == "POST":
        post = Post.objects.get(id=post_id)
        if request.user.id == post.author.id:
            if db_delete:
                post.delete()
            else:
                post.is_visible = False
                post.save()
                # post.delete()
        return redirect('post:post-list')

@login_required
def post_add(request):
    user = request.user

    def create_post_comment_from_data(file, comment_content):
        post = Post(author=user, photo=file)
        post.save()
        if comment_content.strip() != '':
            post.add_comment(user, comment_content)

    if request.method == "POST":
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            files = request.FILES.getlist('photo')
            comment_content = form.cleaned_data.get('content', '')
            for file in files:
                create_post_comment_from_data(file, comment_content)

            return redirect('post:post-list')
    else:
        form = PostForm()
    context = {
        'form': form
    }

    return render(request, 'post/post-add.html', context)

django_app/templates/post/post-add.html
{% extends 'common/base.html' %}
{% block content %}
<div class="photo-add-container">

    <form action="" method="POST" enctype="multipart/form-data">{% csrf_token %}
        {{ form }}
        <button type="submit">POST</button>
    </form>

</div>

{% endblock %}

django_app/templates/post/post-detail.html
{% extends 'common/base.html' %}
{% block content %}



<div>POST: {{ post.id }}</div>
<br>
<div>Date: {{ post.created_date }}</div>
<br>
<div>By: {{ post.author.username}}</div>
<br>
<div>Content:{{ post.content|linebreaks }}</div>
<br>
{% if post.like_users.all %}
<div style="color:red"> Liked by:
    {% for like_user in post.like_users.all %}
    <li>{{ like_user }}</li>
    {% endfor %}
</div>
{% endif %}
<br>
<form action="{% url 'post:post_like_toggle' post_id=post.id %}" method="POST">
{% csrf_token %}
    <button type="submit">
        {% if user in post.like_users.all %}
        UNLIKE
        {% else %}
        LIKE
        {% endif %}
    </button>
</form>

<div><img src="{{ MEDIA_URL }}{{ post.photo }}"></div>
<br>
{% if post.comment_set.all %}
{% for comment in post.comment_set.all %}
<div style="color:crimson">{{ comment.author.username }}: {{ comment.content }}
    <form action ="{% url 'post:comment_delete' post_id=post.id comment_id=comment.id %}" method="POST" >{% csrf_token %}
<button type="submit">DELETE</button>

</form>
</div>
{% endfor %}
{% endif %}
<div>
    <form action="{% url 'post:comment_add' post_id=post.id %}" method="POST">{% csrf_token %}
        <!--<input type="text" , name="content">-->
        {{ comment_form.content}}
        <button type="submit">Write Comment</button>
    </form>
</div>

{% endblock %}

django_app/templates/post/post-list-s.html
{% extends 'common/base.html' %}
{% block content %}
<div class="post-list-container">
  {% for post in post_list %}
<div>POST: {{ post.id }}</div><br>
  <div>By: {{ post.author.username}}</div><br>
  <div>Content:{{ post.content|linebreaks|truncatechars:30 }}</div><br>
  {% if post.like_users.all %}
  <div> Liked by:
    {% for like_user in post.like_users.all %}
    <p>{{ like_user }}</p>
    {% endfor %}
  </div><br>
  {% endif %}
  <div><a href="{% url 'post:post-detail' post.id %}"><img src="{{ MEDIA_URL }}{{ post.photo }}"></a></div><br>
  {% if post.comment_set.all %}
  {% for comment in post.comment_set.all %}
  <div style="color:salmon">{{ comment.author.username }}: {{ comment.content }}</div>
  {% endfor %}
  {% endif %}
  <!--<form action="{% url 'post:comment_add' post_id=post.id %}" method="POST">{% csrf_token %}-->


  <!--<input type="text" , name="content">-->

  <!--<button type="submit">Write Comment</button>-->
  <!--</form>-->

  {% endfor %}
</div>
{% endblock %}

django_app/templates/post/post-list.html
{% extends 'common/base.html' %}

{% block content %}
<div class="post-list-container">
    {% for post in post_list %}
    <article class="post">
        <header class="post-header">
            <span class="header-username">{{ post.author.username }}</span>
            <span class="header-date">{{ post.created_date }}</span>
            {% if user == post.author %}
            <span class="post-delete clearfix">
        <form class="post-delete-form" action="{% url 'post:post_delete' post_id=post.id %}" method="POST">
          {% csrf_token %}
          <button class="btn-post-delete" type="submit">X</button>
        </form>
      </span>
            {% endif %}
        </header>
        <div class="post-image-container">
            <a href="{% url 'post:post-detail' post.id %}">
                <img src="{{ MEDIA_URL }}{{ post.photo }}" class="post-image">
            </a>
        </div>
        <div class="post-bottom-container">
            <div class="post-content">{{ post.content|linebreaks|truncatechars:30 }}</div>
            <div class="post-like-users">
                {% if post.like_users.all %}
                {{ post.like_count }} Likes
                {% for user in post.like_users.all %}
                {{ user.username }}
                {% endfor %}
                {% endif %}
            </div>
            <div class="post-like-users">

            </div>
            <div class="post-comments">
                {% if post.comment_set.all %}
                {% for comment in post.comment_set.all %}

                <div class="post-comment">
                    <span class="comment-author">{{ comment.author.username }}</span>
                    <span class="comment-content">{{ comment.content }}</span>
                    {% if user == comment.author %}
                    <span class="comment-delete">
            <form class="comment-delete-form"
                  action="{% url 'post:comment_delete' post_id=post.id comment_id=comment.id %}" method="POST">
            {% csrf_token %}
            <button class="btn-comment-delete" type="submit">X</button>
          </form>
        </span>
                    {% endif %}

                </div>
                {% endfor %}
                {% endif %}
            </div>
            <div class="post-comment-form-container clearfix">
                <form action="{% url 'post:post_like_toggle' post_id=post.id %}" method="POST">
                    {% csrf_token %}
                    {% if user in post.like_users.all %}
                    <button href="" class="btn-like sprite-heart-red sprite-logo" type="submit"></button>
                    {% else %}
                    <button href="" class="btn-like sprite-heart-empty sprite-logo" type="submit"></button>
                    {% endif %}
                </form>
            </div>
            <form action="{% url 'post:comment_add' post_id=post.id %}" method="POST">{% csrf_token %}
                <input type="text" placeholder="댓글 달기..." class="input-comment" name="content">
            </form>
        </div>
    </article>
    {% endfor %}
    <a href="{% url 'post:post-add' %}">
        <button class="post-add-btn">ADD POST</button>
    </a>
</div>

{% endblock %}