django_app/instagram/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from . import views

# from django.contrib.staticfiles import views


urlpatterns = [
                  url(r'^admin/', admin.site.urls),
                  url(r'^member/', include('member.urls')),
                  url(r'^post/', include('post.urls')),
                  url(r'^$', views.index, name="index"),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# if settings.DEBUG:
#     urlpatterns += [
#         url(r'^static/(?P<path>.*)$', views.serve)
#     ]

django_app/member/urls.py
from django.conf.urls import url

from . import views

app_name = 'member'
urlpatterns = [
    url(r'^login/$', views.login_view, name='login'),
    url(r'^signup/$', views.signup_modelform_view, name='signup'),
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^profile/photo/$', views.change_profile_image, name='profile-pic-add'),
    url(r'^logout/$', views.logout_view, name='logout'),
]

django_app/post/urls.py
from django.conf.urls import url

from . import views

app_name = 'post'
urlpatterns = [
    url(r'^$', views.post_list, name='post-list'),
    url(r'^(?P<post_id>[0-9]+)/$', views.post_detail, name='post-detail', ),
    url(r'^(?P<post_id>[0-9]+)/comment/add/$', views.comment_add, name='comment_add', ),
    url(r'^(?P<post_id>[0-9]+)/like/toggle$', views.post_like_toggle, name='post_like_toggle', ),
    # url(r'^(?P<post_id>[0-9]+)/comment/(?P<comment_id>[0-9]+)/delete/$',
    #     views.comment_delete,
    url(r'^(?P<post_id>[0-9]+)/comment/(?P<comment_id>[0-9]+)/delete/$',
        views.comment_delete,
        name='comment_delete', ),
    url(r'^add/$', views.post_add, name='post-add'),
    url(r'^(?P<post_id>[0-9]+)/delete/$', views.post_delete, name='post_delete'),
]

django_app/templates/common/base.html
{% load staticfiles %}
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport"
  content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>INSTAGRAM</title>
  <link rel="stylesheet" href="{% static 'css/base.css' %}">
  <link rel="stylesheet" href="{% static 'css/sprites.css' %}">
  <link rel="stylesheet" href="{% static 'css/header.css' %}">
  <link rel="stylesheet" href="{% static 'css/post_list.css' %}">


</head>
<body>
  <div id = "wrap">
    <header>
      <nav>
        <div id="logo-wrap">
          <span class="nav-left nav-group">
            <a href="{% url 'post:post-list' %}" class ="logo sprite-logo"></a>
          </span>
          <span class="nav-group nav-center">
            <input class="search" type="text" placeholder="search">
          </span>
          <span class="nav-group nav-right">
            <a href="" id="compass" class="mini-logo sprite-logo"></a>
            <a href="" id="heart" class="mini-logo sprite-logo"></a>
            <a href="{% url 'member:profile' %}" id = "user-info" class="mini-logo sprite-logo"></a>
          </span>
        </div>
      </nav>
    </header>

    {% if user.is_authenticated %}

    <div>Welcome! {{ user.username }}</div>
    {% else %}
    <div><a href="{% url 'member:login' %}">Please Login</a></div>

    <br>
    {% endif %}


    {% block content %}
    {% endblock %}
  </div>
</body>
</html>